# Generated by Django 2.1.3 on 2018-11-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=30)),
                ('author', models.CharField(default='作者', max_length=30)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='co_brand/images/')),
                ('text', models.TextField(default='内容')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
