# Generated by Django 2.1.3 on 2018-11-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_brand', '0002_auto_20181119_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='cases/upload_images/co_brand/'),
        ),
    ]
