# Generated by Django 2.1.3 on 2018-12-04 01:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_brand', '0003_auto_20181120_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='text',
        ),
        migrations.AddField(
            model_name='brand',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Content'),
        ),
        migrations.AddField(
            model_name='brand',
            name='introduce',
            field=models.CharField(default='介绍', max_length=100),
        ),
    ]
